import http.server
import socketserver
import os

PORT = 8000

HTML_CONTENT = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SkyWatch-20 Tactical Display Radar</title>
    <style>
        body {
            background-color: #020f05;
            color: #00ff78;
            font-family: 'Courier New', Courier, monospace;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            overflow: hidden;
        }
        h1 {
            margin-bottom: 5px;
            font-size: 20px;
            letter-spacing: 2px;
            text-shadow: 0 0 5px #00ff78;
        }
        #radar-container {
            position: relative;
            width: 600px;
            height: 600px;
            border: 2px solid #005000;
            border-radius: 50%;
            box-shadow: 0 0 20px rgba(0, 255, 120, 0.1);
        }
        canvas {
            position: absolute;
            top: 0;
            left: 0;
            border-radius: 50%;
        }
    </style>
</head>
<body>
    <h1>=== SKYWATCH-20 TACTICAL INTERFACE ===</h1>
    <div id="radar-container">
        <canvas id="radarCanvas" width="600" height="600"></canvas>
    </div>

    <script>
        const canvas = document.getElementById('radarCanvas');
        const ctx = canvas.getContext('2d');
        const cx = canvas.width / 2;
        const cy = canvas.height / 2;
        
        let sweepAngle = 0;
        
        // Mocking the flight path positions generated by our structural physics updates
        let fleet = [
            { id: "UAL104", x: -15, y: -15, vx: 0.1, vy: 0.1, alt: 5.0 },
            { id: "AAL892", x: 15, y: 15, vx: -0.09, vy: -0.09, alt: 4.9 },
            { id: "DAL440", x: -18, y: 10, vx: 0.12, vy: -0.05, alt: 6.2 }
        ];

        let storms = [
            { x: 10, y: 8, radius: 5 },
            { x: -12, y: -10, radius: 6 }
        ];

        function drawRadar() {
            // Clear trail with slight opacity for a beautiful phosphor scan effect
            ctx.fillStyle = 'rgba(2, 15, 5, 0.08)';
            ctx.fillRect(0, 0, canvas.width, canvas.height);

            // 1. Draw Concentric CAD Target Rings
            ctx.strokeStyle = 'rgba(0, 100, 0, 0.4)';
            ctx.lineWidth = 1;
            for (let r = 50; r <= 280; r += 60) {
                ctx.beginPath();
                ctx.arc(cx, cy, r, 0, 2 * Math.PI);
                ctx.stroke();
            }

            // Crosshair Axes
            ctx.beginPath();
            ctx.moveTo(0, cy); ctx.lineTo(canvas.width, cy);
            ctx.moveTo(cx, 0); ctx.lineTo(cx, canvas.height);
            ctx.stroke();

            // 2. Draw Weather Zones
            storms.forEach(storm => {
                ctx.fillStyle = 'rgba(200, 50, 0, 0.02)';
                ctx.strokeStyle = 'rgba(255, 60, 0, 0.05)';
                ctx.beginPath();
                ctx.arc(cx + (storm.x * 12), cy - (storm.y * 12), storm.radius * 12, 0, 2 * Math.PI);
                ctx.fill();
                ctx.stroke();
            });

            // 3. Move and Update Planes (Physics Solver Layer)
            fleet.forEach(ac => {
                ac.x += ac.vx * 0.1;
                ac.y += ac.vy * 0.1;

                // Loop them back if they wander out of limits
                if (Math.abs(ac.x) > 25) ac.x = -ac.x;
                if (Math.abs(ac.y) > 25) ac.y = -ac.y;

                let sx = cx + (ac.x * 12);
                let sy = cy - (ac.y * 12);

                // Check angle relative to the sweep line to trigger bright phosphor hits
                let targetAngle = Math.atan2(ac.y, ac.x);
                if (targetAngle < 0) targetAngle += 2 * Math.PI;
                let diff = Math.abs(sweepAngle - targetAngle);
                
                if (diff < 0.2) {
                    ctx.fillStyle = '#00ffda'; // Fresh Hit Cyan blip
                    ctx.shadowBlur = 10;
                    ctx.shadowColor = '#00ffda';
                } else {
                    ctx.fillStyle = ac.alt > 5.0 ? '#00ff78' : '#00bc56';
                    ctx.shadowBlur = 0;
                }

                ctx.fillRect(sx - 3, sy - 3, 6, 6);
                
                // Display tracking tag identifiers
                ctx.fillStyle = 'rgba(0, 255, 120, 0.6)';
                ctx.font = '9px monospace';
                ctx.fillText(ac.id, sx + 8, sy + 3);
            });
            ctx.shadowBlur = 0; // Reset canvas glow

            // 4. Draw Radar Sweep Beam Line
            let targetX = cx + 290 * Math.cos(sweepAngle);
            let targetY = cy - 290 * Math.sin(sweepAngle);
            
            let gradient = ctx.createLinearGradient(cx, cy, targetX, targetY);
            gradient.addColorStop(0, 'rgba(0, 255, 100, 0.4)');
            gradient.addColorStop(1, 'rgba(0, 255, 100, 0)');
            
            ctx.strokeStyle = gradient;
            ctx.lineWidth = 2;
            ctx.beginPath();
            ctx.moveTo(cx, cy);
            ctx.lineTo(targetX, targetY);
            ctx.stroke();

            // Advance sweeping scan beam velocity bounds
            sweepAngle += 0.015;
            if (sweepAngle >= 2 * Math.PI) sweepAngle -= 2 * Math.PI;

            requestAnimationFrame(drawRadar);
        }

        // Initialize display loop
        drawRadar();
    </script>
</body>
</html>
"""

class RadarHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == '/' or self.path == '/index.html':
            self.send_response(200)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            self.wfile.write(bytes(HTML_CONTENT, "utf8"))
        else:
            self.send_error(404, "File Not Found")

print(f"📡 [SKYWATCH-20] Starting web visualization node on port {PORT}...")
with socketserver.TCPServer(("", PORT), RadarHandler) as httpd:
    print("🚀 Cloud broadcast online! Open the forwarded browser window tab to view details.")
    httpd.serve_forever()
